spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  application:
    name: ms-human
  datasource:
    url: jdbc:mysql://localhost:3306/foo_fighters
    password: rootpassword
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
    enabled: true
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 4444

api:
  url: http://localhost:9090



